title: Nano Markup
description: A lightweight markup language and minimal, indentation-based structured data format. Designed to be a small, human-friendly serialization format for representing strings, mappings, and sequences.
url: https://nohainc.github.io
baseurl: ""
lang: en
repository: nohainc/nohainc.github.io
version: 1.0.0
release_date: 2026-07-24
specification_url: https://github.com/nohainc/nanomarkup.spec/tree/v1.0.0
release_url: https://github.com/nohainc/nanomarkup.spec/releases/tag/v1.0.0
permalink: pretty
strict_front_matter: true
exclude:
  - Gemfile
  - Gemfile.lock
  - tests
  - vendor
